const countries = {
    "ar-SA": "Arabic",
    "bn-IN": "Bengali",
    "de-DE": "German",
    "el-GR": "Greek",
    "en-GB": "English",
    "es-ES": "Spanish",
    "fr-FR": "French",
    "gu-IN": "Gujarati",
    "hi-IN": "Hindi",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "ko-KR": "Korean",
    "ta-LK": "Tamil",
    "te-IN": "Telugu",
}